// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uelbysoaoreoviwcuqer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbGJ5c29hb3Jlb3Zpd2N1cWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjgzNzUsImV4cCI6MjA3MDIwNDM3NX0.GO5Mj9OaJQ8TjUluGOj5yAXI4DzrqGL8n5kxoCz6nog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});